name: Build, Test, and Push to GHCR

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' 

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  
        with: 
          fetch-depth: 0

      - name: Extract tag version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set lowercase username
        run: echo "USERNAME=$(echo $GITHUB_ACTOR | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker image (no cache)
        run: docker build --no-cache -t ghcr.io/${{ env.USERNAME }}/nginx:${{ env.VERSION }} .

      - name: Run container for testing
        run: docker run -d --rm --name test-nginx -p 8080:80 ghcr.io/${{ env.USERNAME }}/nginx:${{ env.VERSION }}

      - name: Wait for container to be ready
        run: sleep 5  

      - name: Test Nginx response
        run: |
          HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:8080)
          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Test failed: Nginx did not return HTTP 200"
            exit 1
          fi
          echo "Test passed: Nginx is running correctly"

      - name: Stop test container
        run: docker stop test-nginx

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ env.USERNAME }}/nginx:${{ env.VERSION }}
