name: Build and Push to GHCR

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  
        with: 
          fetch-depth: 0

      - name: Extract tag version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set lowercase username
        run: echo "USERNAME=$(echo $GITHUB_ACTOR | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker image (no cache)
        run: docker build --no-cache -t ghcr.io/${{ env.USERNAME }}/nginx:${{ env.VERSION }} .

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ env.USERNAME }}/nginx:${{ env.VERSION }}
