name: Build, Push and Deploy

on:
  push:
    tags:
      - "*"  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  

      - name: Extract tag version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set lowercase username
        run: echo "USERNAME=$(echo $GITHUB_ACTOR | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker image (no cache)
        run: docker build --no-cache -t ghcr.io/${{ env.USERNAME }}/nginx:${{ env.VERSION }} .

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ env.USERNAME }}/nginx:${{ env.VERSION }} 

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push  # Kör detta efter att imagen har byggts och pushats

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  

      - name: Extract tag version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set lowercase username
        run: echo "USERNAME=$(echo $GITHUB_ACTOR | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          kubectl cluster-info  # Testa att ansluta till klustret
      

      - name: Update and apply Kubernetes deployment
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|ghcr.io/${{ env.USERNAME }}/nginx:${{ env.VERSION }}|g" nginx-deployment.yml
          kubectl apply -f nginx-deployment.yml
